package com.time_editor.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.time_editor.common.model.Task;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSave<M extends BaseSave<M>> extends Model<M> implements IBean {

	public void setTask(Integer id, String task) {
		Task.me.findById(id).set("content",task).update();
	}
}
