package com.time_editor.common.model.base;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSave<M extends BaseSave<M>> extends Model<M> implements IBean {

	public void setTask(String task) {
		String sql = "select * from task where id = 1";
		Record res = Db.findFirst(sql);
		res.set("content", task);
		set("task", task);
	}
}
